/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type EventReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'event'
}

export type SourceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'source'
}

export type Statement = {
  _id: string
  _type: 'statement'
  _createdAt: string
  _updatedAt: string
  _rev: string
  event?: EventReference
  field?:
    | 'applyBy'
    | 'dates'
    | 'venue'
    | 'free'
    | 'prize'
    | 'travel'
    | 'accommodation'
    | 'eligibility'
    | 'entry'
    | 'sponsors'
    | 'status'
  quote?: string
  source?: SourceReference
  verdict?: 'unresolved' | 'accepted' | 'superseded' | 'incorrect'
  verdictNote?: string
  kbIssueUrl?: string
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  series?: string
  year?: number
  slug?: Slug
  officialUrl?: string
  type?: 'hackathon' | 'competition' | 'challenge' | 'gamejam'
  organizer?: string
  sponsors?: Array<string>
  format?: 'onsite' | 'hybrid'
  venues?: Array<{
    city?: string
    country?: string
    _key: string
  }>
  eventStart?: string
  eventEnd?: string
  applyBy?: string
  registrationStatus?: 'announced' | 'applications-open' | 'applications-closed'
  maxTeamSize?: number
  tags?: Array<string>
  free?: SourcedClaim
  studentsOnly?: SourcedClaim
  travelCovered?: SourcedClaim
  accommodation?: SourcedClaim
  prizeIsCash?: SourcedClaim
  prizeAmount?: number
  prizeCurrency?: string
}

export type SourcedClaim = {
  _type: 'sourcedClaim'
  value?: 'yes' | 'no' | 'not-stated'
  note?: string
  basis?: SourceReference
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Source = {
  _id: string
  _type: 'source'
  _createdAt: string
  _updatedAt: string
  _rev: string
  url?: string
  title?: string
  publisher?: string
  kind?: 'official-rules' | 'official' | 'platform' | 'aggregator' | 'third-party'
  publishedOn?: string
  readOn?: string
  aboutEdition?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | EventReference
  | SourceReference
  | Statement
  | Event
  | SourcedClaim
  | Slug
  | Source
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: scripts/seed.ts
// Variable: sourceIdsQuery
// Query: *[_type == "source"]{_id, url}
export type SourceIdsQueryResult = Array<{
  _id: string
  url: string | null
}>

// Source: scripts/seed.ts
// Variable: eventIdsQuery
// Query: *[_type == "event"]{_id, "slug": slug.current}
export type EventIdsQueryResult = Array<{
  _id: string
  slug: string | null
}>

// Source: scripts/seed.ts
// Variable: statementIdsQuery
// Query: *[_type == "statement"]._id
export type StatementIdsQueryResult = Array<string>

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "source"]{_id, url}': SourceIdsQueryResult
    '*[_type == "event"]{_id, "slug": slug.current}': EventIdsQueryResult
    '*[_type == "statement"]._id': StatementIdsQueryResult
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
